# Versioning System
FUTURE_BASE_VERSION = v2.1

# Set all versions
FUTURE_BUILD_TYPE ?= UNOFFICIAL
FUTURE_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
FUTURE_PLATFORM_VERSION := 9.0
FUTURE_BASE_SET_VERSION = 2.0
TARGET_PRODUCT_SHORT := $(subst aosp_,,$(FUTURE_BUILD))

ifeq ($(IS_PIE_VERSION), true)
FUTURE_VERSION := Future-OS_$(FUTURE_BUILD)-$(FUTURE_PLATFORM_VERSION)-$(FUTURE_BUILD_DATE)-$(FUTURE_BUILD_TYPE)
ROM_FINGERPRINT := Future-OS/$(FUTURE_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(FUTURE_BUILD_DATE)
else
FUTURE_VERSION := Future-OS_$(FUTURE_BUILD)-$(FUTURE_PLATFORM_VERSION)-$(FUTURE_BUILD_DATE)-$(FUTURE_BUILD_TYPE)
ROM_FINGERPRINT := Future-OS/$(FUTURE_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(FUTURE_BUILD_DATE)
endif

PRODUCT_PROPERTIES := \
    org.future.version=$(FUTURE_VERSION) \
    org.future.build_date=$(FUTURE_BUILD_DATE) \
    org.future.build_type=$(FUTURE_BUILD_TYPE) \
    org.future.fingerprint=$(ROM_FINGERPRINT)
    org.future.build.version=$(FUTURE_BUILD_VERSION) \